# Generated by Django 5.2.5 on 2025-08-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('website_url', models.URLField(help_text='Website URL to capture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=10)),
                ('device_name', models.CharField(help_text='Specific device name (e.g., iPhone 12)', max_length=100)),
                ('width', models.IntegerField(help_text='Screenshot width in pixels')),
                ('height', models.IntegerField(help_text='Screenshot height in pixels')),
                ('original_path', models.CharField(help_text='Path to original screenshot', max_length=500)),
                ('mockup_path', models.CharField(help_text='Path to mockup image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='screenshots.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
