# Generated by Django 5.2.5 on 2025-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_id',
            field=models.CharField(default=1, help_text='User ID who created the project', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='creator_name',
            field=models.CharField(default='femi', help_text='Name of the creator', max_length=200),
        ),
    ]
