# Generated by Django 5.2.5 on 2025-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_project_creator_id_project_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_delay',
            field=models.IntegerField(default=3000, help_text='Delay after page load in ms'),
        ),
        migrations.AddField(
            model_name='project',
            name='scroll_delay',
            field=models.IntegerField(default=50, help_text='Delay per scroll step in ms'),
        ),
        migrations.AddField(
            model_name='project',
            name='timeout',
            field=models.IntegerField(default=120000, help_text='Global timeout in ms'),
        ),
    ]
