# Generated by Django 5.2.5 on 2025-09-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0003_project_page_delay_project_scroll_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='page_delay',
            field=models.IntegerField(default=1000, help_text='Delay after page load in ms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scroll_delay',
            field=models.IntegerField(default=500, help_text='Delay per scroll step in ms'),
        ),
    ]
