# Generated by Django 5.2.5 on 2025-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0005_alter_project_page_delay_alter_project_scroll_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='page_delay',
            field=models.IntegerField(default=3000, help_text='Delay after page load in ms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scroll_delay',
            field=models.IntegerField(default=100, help_text='Delay per scroll step in ms'),
        ),
    ]
